
// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview This flow estimates the calorie count of a meal from an image,
 * identifies the dish, lists ingredients, and suggests a recipe idea.
 *
 * - guessCaloriesFromImage - Estimates calories, identifies dish, ingredients, and recipe idea.
 * - GuessCaloriesFromImageInput - The input type for the guessCaloriesFromImage function.
 * - GuessCaloriesFromImageOutput - The return type for the guessCaloriesFromImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GuessCaloriesFromImageInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a meal, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type GuessCaloriesFromImageInput = z.infer<
  typeof GuessCaloriesFromImageInputSchema
>;

const GuessCaloriesFromImageOutputSchema = z.object({
  dishName: z.string().describe('The name of the dish identified in the photo.'),
  ingredients: z.array(z.string()).describe('List of key ingredients identified in the meal.'),
  estimatedCalories: z
    .number()
    .describe('The estimated calorie count of the meal.'),
  recipeIdea: z.string().describe('A brief recipe idea or key preparation steps for the dish (2-3 sentences).')
});
export type GuessCaloriesFromImageOutput = z.infer<
  typeof GuessCaloriesFromImageOutputSchema
>;

export async function guessCaloriesFromImage(
  input: GuessCaloriesFromImageInput
): Promise<GuessCaloriesFromImageOutput> {
  return guessCaloriesFromImageFlow(input);
}

const guessCaloriesFromImagePrompt = ai.definePrompt({
  name: 'guessCaloriesFromImagePrompt',
  input: {schema: GuessCaloriesFromImageInputSchema},
  output: {schema: GuessCaloriesFromImageOutputSchema},
  prompt: `You are an expert nutritionist and chef. You will be provided with a photo of a meal.
Based on the photo:
1. Identify the name of the dish.
2. List the key ingredients you can identify in the meal.
3. Estimate the total calories for the meal shown.
4. Provide a brief (2-3 sentences) recipe idea or key preparation steps for this dish or a similar one.

Respond with a JSON object.
Photo: {{media url=photoDataUri}}`,
});

const guessCaloriesFromImageFlow = ai.defineFlow(
  {
    name: 'guessCaloriesFromImageFlow',
    inputSchema: GuessCaloriesFromImageInputSchema,
    outputSchema: GuessCaloriesFromImageOutputSchema,
  },
  async input => {
    const {output} = await guessCaloriesFromImagePrompt(input);
    return output!;
  }
);
