import type { Recipe } from '@/types';

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    name: 'Classic Spaghetti Carbonara',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Italian',
    ingredients: ['Spaghetti', 'Eggs', 'Pancetta', 'Pecorino Romano', 'Black Pepper'],
    dietaryRestrictions: [],
    calories: 600,
    description: 'A creamy and delicious classic Italian pasta dish.',
    preparationTime: '30 minutes',
    servings: 4,
  },
  {
    id: '2',
    name: 'Vegan Lentil Soup',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Global',
    ingredients: ['Red Lentils', 'Vegetable Broth', 'Carrots', 'Celery', 'Onion', 'Spices'],
    dietaryRestrictions: ['Vegan', 'Gluten-Free'],
    calories: 350,
    description: 'A hearty and nutritious vegan soup perfect for a cold day.',
    preparationTime: '45 minutes',
    servings: 6,
  },
  {
    id: '3',
    name: 'Chicken Teriyaki Stir-fry',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Japanese',
    ingredients: ['Chicken Breast', 'Broccoli', 'Bell Peppers', 'Soy Sauce', 'Mirin', 'Sugar', 'Ginger', 'Garlic'],
    dietaryRestrictions: [],
    calories: 450,
    description: 'A quick and flavorful chicken stir-fry with a sweet and savory teriyaki sauce.',
    preparationTime: '25 minutes',
    servings: 3,
  },
  {
    id: '4',
    name: 'Quinoa Salad with Roasted Vegetables',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Mediterranean',
    ingredients: ['Quinoa', 'Zucchini', 'Eggplant', 'Red Onion', 'Cherry Tomatoes', 'Lemon Vinaigrette'],
    dietaryRestrictions: ['Vegan', 'Gluten-Free'],
    calories: 400,
    description: 'A light and refreshing quinoa salad packed with roasted vegetables and a zesty dressing.',
    preparationTime: '50 minutes',
    servings: 4,
  },
];
