
import type { Recipe } from '@/types';

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    name: 'Classic Spaghetti Carbonara',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Italian',
    ingredients: ['Spaghetti', 'Eggs', 'Pancetta', 'Pecorino Romano', 'Black Pepper'],
    dietaryRestrictions: [],
    calories: 600,
    description: 'A creamy and delicious classic Italian pasta dish, rich in flavor and tradition.',
    preparationTime: '30 minutes',
    servings: 4,
  },
  {
    id: '2',
    name: 'Vegan Lentil Soup',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Global',
    ingredients: ['Red Lentils', 'Vegetable Broth', 'Carrots', 'Celery', 'Onion', 'Turmeric', 'Cumin'],
    dietaryRestrictions: ['Vegan', 'Gluten-Free'],
    calories: 350,
    description: 'A hearty and nutritious vegan soup perfect for a cold day, packed with vegetables and spices.',
    preparationTime: '45 minutes',
    servings: 6,
  },
  {
    id: '3',
    name: 'Chicken Teriyaki Stir-fry',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Japanese',
    ingredients: ['Chicken Breast', 'Broccoli', 'Bell Peppers', 'Soy Sauce', 'Mirin', 'Sugar', 'Ginger', 'Garlic', 'Sesame Oil'],
    dietaryRestrictions: [],
    calories: 450,
    description: 'A quick and flavorful chicken stir-fry with a sweet and savory teriyaki sauce and crisp vegetables.',
    preparationTime: '25 minutes',
    servings: 3,
  },
  {
    id: '4',
    name: 'Quinoa Salad with Roasted Vegetables',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Mediterranean',
    ingredients: ['Quinoa', 'Zucchini', 'Eggplant', 'Red Onion', 'Cherry Tomatoes', 'Feta Cheese', 'Lemon Vinaigrette', 'Kalamata Olives'],
    dietaryRestrictions: ['Gluten-Free', 'Vegetarian'],
    calories: 400,
    description: 'A light and refreshing quinoa salad packed with colorful roasted vegetables and a zesty lemon dressing.',
    preparationTime: '50 minutes',
    servings: 4,
  },
  {
    id: '5',
    name: 'Beef Tacos with Homemade Salsa',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Mexican',
    ingredients: ['Ground Beef', 'Taco Shells', 'Lettuce', 'Tomato', 'Onion', 'Cilantro', 'Lime', 'Avocado', 'Cheese'],
    dietaryRestrictions: [],
    calories: 520,
    description: 'Flavorful beef tacos with fresh homemade salsa, perfect for a fun and easy weeknight meal.',
    preparationTime: '35 minutes',
    servings: 4,
  },
  {
    id: '6',
    name: 'Thai Green Curry with Tofu',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Thai',
    ingredients: ['Tofu', 'Green Curry Paste', 'Coconut Milk', 'Bamboo Shoots', 'Bell Peppers', 'Thai Basil', 'Jasmine Rice'],
    dietaryRestrictions: ['Vegan', 'Gluten-Free'],
    calories: 480,
    description: 'Aromatic and spicy Thai green curry with crispy tofu and a medley of vegetables, served over jasmine rice.',
    preparationTime: '40 minutes',
    servings: 4,
  },
  {
    id: '7',
    name: 'Mushroom Risotto',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Italian',
    ingredients: ['Arborio Rice', 'Mushrooms (Cremini, Porcini)', 'Vegetable Broth', 'White Wine', 'Parmesan Cheese', 'Onion', 'Garlic'],
    dietaryRestrictions: ['Vegetarian'],
    calories: 550,
    description: 'Creamy and decadent mushroom risotto made with Arborio rice and a mix of fresh mushrooms.',
    preparationTime: '1 hour',
    servings: 3,
  },
  {
    id: '8',
    name: 'Indian Butter Chicken',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Indian',
    ingredients: ['Chicken Thighs', 'Tomato Puree', 'Heavy Cream', 'Butter', 'Garam Masala', 'Ginger-Garlic Paste', 'Kasuri Methi'],
    dietaryRestrictions: [],
    calories: 650,
    description: 'A rich and creamy Indian butter chicken curry, mildly spiced and full of flavor. Best served with naan or rice.',
    preparationTime: '50 minutes',
    servings: 4,
  }
];
