
import type { Recipe } from '@/types';

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    name: 'Classic Spaghetti Carbonara',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Italian',
    ingredients: ['200g Spaghetti', '2 large Eggs', '50g Pancetta or Guanciale, diced', '25g Pecorino Romano cheese, grated', 'Freshly ground Black Pepper', 'Salt to taste'],
    instructions: [
      'Cook spaghetti according to package directions. Reserve 1/2 cup of pasta water.',
      'While pasta cooks, fry pancetta in a skillet until crispy. Remove from heat.',
      'In a bowl, whisk eggs, grated Pecorino Romano, and a generous amount of black pepper.',
      'Drain pasta and immediately add it to the skillet with pancetta. Toss to combine.',
      'Quickly pour in the egg mixture, stirring constantly to prevent eggs from scrambling. If too thick, add a little reserved pasta water until creamy.',
      'Serve immediately with extra grated cheese and pepper.'
    ],
    dietaryRestrictions: [],
    calories: 600,
    description: 'A creamy and delicious classic Italian pasta dish, rich in flavor and tradition.',
    preparationTime: '30 minutes',
    servings: 2,
    viewCount: 1250,
    saveCount: 320,
  },
  {
    id: '2',
    name: 'Vegan Lentil Soup',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Global',
    ingredients: ['1 cup Red Lentils, rinsed', '4 cups Vegetable Broth', '1 medium Carrot, diced', '1 Celery stalk, diced', '1 medium Onion, chopped', '2 cloves Garlic, minced', '1 tsp Turmeric powder', '1 tsp Cumin powder', 'Salt and Pepper to taste', '1 tbsp Olive Oil'],
    instructions: [
      'Heat olive oil in a large pot or Dutch oven over medium heat.',
      'Add onion, carrot, and celery. Cook until softened, about 5-7 minutes.',
      'Stir in garlic, turmeric, and cumin. Cook for 1 minute more until fragrant.',
      'Add rinsed lentils and vegetable broth. Bring to a boil.',
      'Reduce heat, cover, and simmer for 20-25 minutes, or until lentils are tender.',
      'Season with salt and pepper. Serve hot, optionally with a squeeze of lemon juice.'
    ],
    dietaryRestrictions: ['Vegan', 'Gluten-Free'],
    calories: 350,
    description: 'A hearty and nutritious vegan soup perfect for a cold day, packed with vegetables and spices.',
    preparationTime: '45 minutes',
    servings: 4,
    viewCount: 890,
    saveCount: 150,
  },
  {
    id: '3',
    name: 'Chicken Teriyaki Stir-fry',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Japanese',
    ingredients: ['1 lb Chicken Breast, cut into strips', '1 head Broccoli, cut into florets', '1 Red Bell Pepper, sliced', '1/4 cup Soy Sauce', '2 tbsp Mirin', '1 tbsp Sugar', '1 tsp Ginger, grated', '1 clove Garlic, minced', '1 tbsp Sesame Oil', 'Cooked Rice for serving'],
    instructions: [
      'In a small bowl, whisk together soy sauce, mirin, sugar, ginger, and garlic for the teriyaki sauce.',
      'Heat sesame oil in a large skillet or wok over medium-high heat.',
      'Add chicken strips and cook until browned and cooked through. Remove from skillet.',
      'Add broccoli and bell pepper to the skillet. Stir-fry for 3-5 minutes until tender-crisp.',
      'Return chicken to the skillet. Pour teriyaki sauce over everything.',
      'Cook, stirring, for 2-3 minutes until sauce has thickened and coated the chicken and vegetables.',
      'Serve hot over cooked rice.'
    ],
    dietaryRestrictions: [],
    calories: 450,
    description: 'A quick and flavorful chicken stir-fry with a sweet and savory teriyaki sauce and crisp vegetables.',
    preparationTime: '25 minutes',
    servings: 3,
    viewCount: 2100,
    saveCount: 550,
  },
  {
    id: '4',
    name: 'Quinoa Salad with Roasted Vegetables',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Mediterranean',
    ingredients: ['1 cup Quinoa, rinsed', '2 cups Water or Vegetable Broth', '1 Zucchini, diced', '1 Eggplant, diced', '1 Red Onion, sliced', '1 cup Cherry Tomatoes, halved', '1/2 cup Feta Cheese, crumbled', '1/4 cup Kalamata Olives, halved', 'Dressing: 3 tbsp Olive Oil, 1 tbsp Lemon Juice, Salt, Pepper'],
    instructions: [
      'Preheat oven to 400°F (200°C). Toss zucchini, eggplant, and red onion with a little olive oil, salt, and pepper. Roast for 20-25 minutes until tender.',
      'Cook quinoa according to package directions using water or broth.',
      'In a small bowl, whisk together dressing ingredients: olive oil, lemon juice, salt, and pepper.',
      'In a large bowl, combine cooked quinoa, roasted vegetables, cherry tomatoes, and Kalamata olives.',
      'Pour dressing over the salad and toss gently to combine.',
      'Sprinkle with feta cheese before serving. Can be served warm or cold.'
    ],
    dietaryRestrictions: ['Gluten-Free', 'Vegetarian'],
    calories: 400,
    description: 'A light and refreshing quinoa salad packed with colorful roasted vegetables and a zesty lemon dressing.',
    preparationTime: '50 minutes',
    servings: 4,
    viewCount: 750,
    saveCount: 210,
  },
  {
    id: '5',
    name: 'Beef Tacos with Homemade Salsa',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Mexican',
    ingredients: ['1 lb Ground Beef', '1 packet Taco Seasoning', '12 Taco Shells (hard or soft)', 'Toppings: Shredded Lettuce, Diced Tomatoes, Chopped Onion, Shredded Cheese, Sour Cream', 'Salsa: 2 ripe Tomatoes, diced; 1/2 Red Onion, finely chopped; 1 Jalapeño, minced (optional); 1/4 cup Cilantro, chopped; Juice of 1 Lime; Salt to taste'],
    instructions: [
      'For the salsa: In a medium bowl, combine diced tomatoes, red onion, jalapeño (if using), cilantro, lime juice, and salt. Mix well and set aside.',
      'Cook ground beef in a skillet over medium heat until browned. Drain excess fat.',
      'Stir in taco seasoning and water according to package directions. Simmer for 5-7 minutes.',
      'Warm taco shells according to package directions.',
      'Assemble tacos: Fill shells with beef mixture, then add desired toppings and homemade salsa.'
    ],
    dietaryRestrictions: [],
    calories: 520,
    description: 'Flavorful beef tacos with fresh homemade salsa, perfect for a fun and easy weeknight meal.',
    preparationTime: '35 minutes',
    servings: 4,
    viewCount: 1800,
    saveCount: 480,
  },
  {
    id: '6',
    name: 'Thai Green Curry with Tofu',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Thai',
    ingredients: ['1 block (14oz) Firm Tofu, pressed and cubed', '2 tbsp Green Curry Paste', '1 can (13.5oz) Coconut Milk', '1 cup Bamboo Shoots, sliced', '1 Red Bell Pepper, sliced', '1/2 cup Thai Basil leaves', '1 tbsp Soy Sauce (or fish sauce if not vegan)', '1 tsp Sugar', 'Jasmine Rice for serving'],
    instructions: [
      'Optional: Pan-fry or bake tofu cubes until lightly golden. Set aside.',
      'In a large pot or wok, heat 1/4 cup of coconut milk over medium heat. Add green curry paste and cook for 1-2 minutes until fragrant.',
      'Stir in the remaining coconut milk, bamboo shoots, and bell pepper. Bring to a simmer.',
      'Add tofu, soy sauce, and sugar. Simmer for 5-10 minutes, allowing flavors to meld.',
      'Stir in Thai basil leaves just before serving.',
      'Serve hot with jasmine rice.'
    ],
    dietaryRestrictions: ['Vegan', 'Gluten-Free'],
    calories: 480,
    description: 'Aromatic and spicy Thai green curry with crispy tofu and a medley of vegetables, served over jasmine rice.',
    preparationTime: '40 minutes',
    servings: 4,
    viewCount: 1150,
    saveCount: 290,
  },
  {
    id: '7',
    name: 'Mushroom Risotto',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Italian',
    ingredients: ['1.5 cups Arborio Rice', '8 oz Mushrooms (Cremini, Porcini), sliced', '4-5 cups Vegetable Broth, warmed', '1/2 cup Dry White Wine', '1/2 cup Parmesan Cheese, grated', '1 small Onion, finely chopped', '2 cloves Garlic, minced', '2 tbsp Olive Oil', '1 tbsp Butter', 'Salt and Pepper to taste', 'Fresh Parsley, chopped for garnish'],
    instructions: [
      'Heat olive oil and butter in a large, heavy-bottomed pot or Dutch oven over medium heat.',
      'Add onion and cook until softened, about 3-5 minutes. Add garlic and mushrooms, cook until mushrooms are browned and their liquid has evaporated.',
      'Add Arborio rice to the pot and stir for 1-2 minutes until grains are translucent at the edges.',
      'Pour in white wine and cook, stirring constantly, until fully absorbed.',
      'Add a ladleful (about 1/2 cup) of warm broth to the rice, stirring continuously until absorbed. Continue adding broth, one ladleful at a time, waiting until each addition is absorbed before adding the next. This process should take about 20-25 minutes.',
      'Once the rice is creamy and al dente, remove from heat. Stir in grated Parmesan cheese.',
      'Season with salt and pepper to taste. Garnish with fresh parsley and serve immediately.'
    ],
    dietaryRestrictions: ['Vegetarian'],
    calories: 550,
    description: 'Creamy and decadent mushroom risotto made with Arborio rice and a mix of fresh mushrooms.',
    preparationTime: '1 hour',
    servings: 3,
    viewCount: 980,
    saveCount: 250,
  },
  {
    id: '8',
    name: 'Indian Butter Chicken',
    imageUrl: 'https://placehold.co/600x400.png',
    cuisine: 'Indian',
    ingredients: ['1.5 lbs Chicken Thighs, boneless, skinless, cut into pieces', 'Marinade: 1/2 cup Plain Yogurt, 1 tbsp Ginger-Garlic Paste, 1 tsp Turmeric, 1 tsp Garam Masala, 1/2 tsp Cumin, Salt', 'Sauce: 1 tbsp Oil, 1 tbsp Butter, 1 large Onion, finely chopped, 1 tbsp Ginger-Garlic Paste, 1 (14oz) can Tomato Puree or crushed tomatoes, 1 tsp Garam Masala, 1 tsp Kashmiri Red Chili powder (optional, for color), 1/2 cup Heavy Cream, 1 tbsp Kasuri Methi (dried fenugreek leaves), Salt to taste, Sugar to taste (optional, to balance acidity)'],
    instructions: [
      'In a bowl, combine chicken pieces with all marinade ingredients. Mix well, cover, and refrigerate for at least 30 minutes (or up to 4 hours).',
      'Heat oil and butter in a large pot or Dutch oven over medium heat. Add chopped onion and cook until golden brown.',
      'Add ginger-garlic paste and cook for 1 minute until fragrant.',
      'Stir in tomato puree, garam masala, and Kashmiri red chili powder. Cook for 5-7 minutes, until sauce thickens slightly.',
      'Add marinated chicken to the pot. Cook for 10-15 minutes, stirring occasionally, until chicken is cooked through.',
      'Reduce heat to low. Stir in heavy cream and kasuri methi. Simmer for 5 more minutes. Do not boil.',
      'Taste and adjust seasoning with salt and a pinch of sugar if needed.',
      'Serve hot with naan bread or basmati rice.'
    ],
    dietaryRestrictions: [],
    calories: 650,
    description: 'A rich and creamy Indian butter chicken curry, mildly spiced and full of flavor. Best served with naan or rice.',
    preparationTime: '50 minutes',
    servings: 4,
    viewCount: 3200,
    saveCount: 850,
  }
];
