
export interface Recipe {
  id: string;
  name: string;
  imageUrl: string;
  cuisine: string;
  ingredients: string[];
  instructions: string[];
  dietaryRestrictions: string[];
  calories?: number;
  description: string;
  preparationTime: string;
  servings: number;
  viewCount?: number;
  saveCount?: number;
}

export interface DetailedRecipe {
  name: string;
  description: string;
  preparationTime: string;
  cookingTime: string;
  servings: string;
  ingredientsList: string[];
  instructionsList: string[];
}

export interface AIEstimation {
  dishName: string;
  estimatedCalories: number;
  identifiedIngredients: string[];
  generatedRecipe: DetailedRecipe;
}

export interface IngredientNutritionInfo {
  ingredient: string;
  calories: number;
  protein: string;
  fat: string;
  carbs: string;
  source: string;
}

// SavedMeal type for Firestore
export interface SavedMeal {
  id: string; // Firestore document ID
  userId: string; // Firebase Auth User ID
  uploadedImagePreview: string; // Data URI of the uploaded image
  aiEstimation: AIEstimation;
  savedAt: string; // ISO string for the timestamp (consider using Firestore Timestamp type)
}

// Type for data being written to Firestore (id is auto-generated by Firestore)
export type NewSavedMealData = Omit<SavedMeal, 'id'>;
